# Generated by Django 3.1.2 on 2025-12-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passport_number', models.CharField(max_length=50)),
                ('nin', models.CharField(blank=True, max_length=50, verbose_name='NIN')),
                ('district', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport_photos', 'Passport Photos'), ('yellow_fever', 'Yellow Fever Certificate')], max_length=50)),
                ('file', models.FileField(upload_to=documents_app.models.client_folder_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents_app.client')),
            ],
        ),
    ]
