# Generated by Django 3.1.2 on 2025-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('passport_photos', 'Passport Photos'), ('passport_book', 'Passport Book Photos'), ('yellow_fever', 'Yellow Fever Certificate')], max_length=50),
        ),
    ]
