# Generated by Django 3.1.2 on 2025-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0002_auto_20251205_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('passport_photos', 'Passport Photos'), ('passport_book', 'Passport Book Photos'), ('yellow_fever', 'Yellow Fever Certificate'), ('complete_pdf', 'Complete PDF Package'), ('other', 'Other Documents')], max_length=50),
        ),
    ]
